sudo: required
services: 
  - docker

before_install:
  - docker build -t zhangchiwang/reactapp -f Dockerfile.dev .

script:
  - docker run -e CI=true zhangchiwang/reactapp npm run test  

language: generic

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Reactapp"
  env: "Reactapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-494337673359"
  bucket_path: "Reactapp"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY



