sudo: required
services: 
  - docker

before_install:
  - docker build -t zhangchiwang/reactapp -f Dockerfile.dev .

script:
  - docker run -e CI=true zhangchiawng/test-repo npm run test  

language: generic

  
